from __future__ import annotations

LIMITE_LONGITUD_LINEA: int = 10000
LIMITE_TAMANIO_ARCHIVO: int = 10 * 1024 * 1024
LIMITE_PROFUNDIDAD_NESTING: int = 50
LIMITE_CANTIDAD_TOKENES: int = 100_000
LIMITE_LONGITUD_IDENTIFICADOR: int = 256
LIMITE_CANTIDAD_COLUMNAS_SELECT: int = 1000
LIMITE_CANTIDAD_JOINES: int = 20
LIMITE_CANTIDAD_EXPRESIONES_WHERE: int = 200
